name: "PR Style Check"

on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: "18.16.0"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Check
        run: pnpm check && pnpm lint
